import Link from "next/link";
import { Sparkles, Github } from "lucide-react";

export default function Footer() {
  return (
    <footer className="border-t border-border/60 bg-background">
      <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center justify-between gap-6 md:flex-row">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-brand">
              <Sparkles className="text-white" size={14} />
            </div>
            <span className="font-bold">
              Lumora <span className="text-gradient">AI</span>
            </span>
          </div>

          <nav className="flex flex-wrap items-center justify-center gap-6 text-sm text-gray-400">
            <Link href="/" className="hover:text-white">
              Home
            </Link>
            <Link href="/image" className="hover:text-white">
              Image Generator
            </Link>
            <Link href="/video" className="hover:text-white">
              Video Generator
            </Link>
            <a
              href="https://github.com"
              target="_blank"
              rel="noreferrer"
              className="flex items-center gap-1.5 hover:text-white"
            >
              <Github size={16} /> Source
            </a>
          </nav>
        </div>

        <div className="mt-8 border-t border-border/60 pt-6 text-center text-xs text-gray-500">
          <p>
            Built with free, open AI image generation. Images are generated by
            third-party models and may occasionally produce unexpected
            results.
          </p>
          <p className="mt-2">
            © {new Date().getFullYear()} Lumora AI. All generations are free
            to use.
          </p>
        </div>
      </div>
    </footer>
  );
}
